In [1]:
import torch

In [3]:
x = torch.Tensor([3, 7])
y = torch.Tensor([2, 1])

print(x * y)

tensor([6., 7.])


In [4]:
zero = torch.zeros([3, 4])

print(zero)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [5]:
rand = torch.rand([3, 4])

print(rand)

tensor([[0.6779, 0.7645, 0.8062, 0.1782],
        [0.7853, 0.5112, 0.7157, 0.4686],
        [0.5391, 0.7477, 0.7438, 0.5230]])


In [6]:
rand.view([2, 6])

tensor([[0.6779, 0.7645, 0.8062, 0.1782, 0.7853, 0.5112],
        [0.7157, 0.4686, 0.5391, 0.7477, 0.7438, 0.5230]])

In [7]:
print(rand)

tensor([[0.6779, 0.7645, 0.8062, 0.1782],
        [0.7853, 0.5112, 0.7157, 0.4686],
        [0.5391, 0.7477, 0.7438, 0.5230]])


In [8]:
rand = rand.view([2, 6])

print(rand)

tensor([[0.6779, 0.7645, 0.8062, 0.1782, 0.7853, 0.5112],
        [0.7157, 0.4686, 0.5391, 0.7477, 0.7438, 0.5230]])


In [10]:
rand.shape

torch.Size([2, 6])

In [11]:
zero.shape

torch.Size([3, 4])